### ISSUE TITLE
[new device] Corsair  Virtuoso (headset) support

### ISSUE THREAD

**Issue by infelicitatis** [ckb-next/ckb-next#673] opened 2020-12-16 18:10 UTC
Woudl be really really nice, since my headset batteries get drain super fast due to exesive lightning since i switched to linux. also it would be nice if i would get control over the monitoring and equalizing features.

**Comment by rvl** [comment] 2021-07-07 01:27
This is a duplicate of #579.

**Closed** 2022-01-20 10:54 UTC
