### ISSUE TITLE
M65 RGB Elite DPI Limit

### ISSUE THREAD

**Issue by robert78901** [ckb-next/ckb-next#452] opened 2019-08-05 00:13 UTC
M65 Elite RGB in ckb-next 0.4.0 is limited to 12000 DPI rather than 18000 DPI

**Comment by tatokis** [comment] 2019-08-15 22:27
Duplicate of https://github.com/ckb-next/ckb-next/issues/197

**Closed by tatokis** 2019-08-15 22:27 UTC
Labels: bug

**Comment by tatokis** [comment] 2019-08-16 00:29
This should be fixed now. Please have a look at https://github.com/ckb-next/ckb-next/issues/197#issuecomment-521842565
