### ISSUE TITLE
Caps Lock/Num Lock indication delay issue is back.

### ISSUE THREAD

**Issue by HeathenHacks** [ckb-next/ckb-next#881] opened 2022-09-21 05:00 UTC
- Search in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
- If possible, try the latest code by building the software manually.
- File unrelated issues separately.

**Click the `Generate Report` button in the `Settings` tab of the ckb-next user interface and attach the generated report to this issue.**

### Source
How and where did you get this program, e.g.:
  * Package from AUR/PPA/COPR/...
  * Built manually using quickinstall script

## Logs & crash reports

Attach:
 * The generated report from the section above
 * Any additional crash reports you've managed to gather

## What is the program's current behaviour?

- Tried both the AUR and Build from source installation and still having the same issue.
- Seems like both Caps Lock, Scroll Lock and Num Lock indicators are having about 2-3 secs. of delay.

## What is the expected behaviour of the program?

-The LED indicator should light up or turn off instantly.

## Any other notes & comments?

- #[Currently experiencing this closed issue](https://github.com/ckb-next/ckb-next/issues/539)
- It happened after updating to version 1:0.5.0.r44.gdd4c495d-1
[ckb-next-report-1663736435.gz](https://github.com/ckb-next/ckb-next/files/9613120/ckb-next-report-1663736435.gz)

- I was using the master branch of the program when the issue occurred. 
- Purged it from my system and then built it from source and still having the same issue.
- *Forgot to mention that switching profiles takes like 1-2 secs, too.

Additional information:
ArcoLinux
Arch: 5.19.9-arch1-1
Plasma 5.25.5
[ckb-next-report-1663734832.gz](https://github.com/ckb-next/ckb-next/files/9613032/ckb-next-report-1663734832.gz)

**Comment by tatokis** [comment] 2022-09-23 21:50
Technically this issue was opened first, however it looks like this is also caused by https://github.com/ckb-next/ckb-next/issues/882 and since that has the actual commit that introduced the issue and a workaround, I'm closing this as a duplicate of that one.

**Closed by tatokis** 2022-09-23 21:50 UTC
Labels: bug
