### ISSUE TITLE
Support for the K95 RGB Platinum XT

### ISSUE THREAD

**Issue by amicharski** [ckb-next/ckb-next#827] opened 2022-05-09 00:42 UTC
## What is the program's current behaviour?

Currently the K95 RGB Platinum XT is not supported.

## What would you like it to do instead?

I would like support for the K95 RGB Platinum XT.

**Comment by fleischie** [comment] 2022-05-09 07:20
Duplicate of #543

**Closed by fleischie** 2022-05-09 07:20 UTC
Labels: enhancement
