### ISSUE TITLE
Corsair KB K57

### ISSUE THREAD

**Issue by steveothesane** [ckb-next/ckb-next#1047] opened 2024-03-11 03:02 UTC
### What kind of device is it?

Keyboard

### What is the name of the device?

K57 Wireless RGB Gaming Keyboard

### Link to Corsair's Product Page

https://www.corsair.com/us/en/p/keyboards/ch-925c015-na/k57-rgb-wireless-gaming-keyboard-na-ch-925c015-na

### Additional Details

Add any additional details here.
I have been using this KB successfully with ckb-next for quite some time and have not run into any issues.  Can we take this KB from Experimental to Supported?  What if anything would you like from me to help support this?  I am currently using Linux Parrot 6.5.0-13parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1parrot1 (2023-12-19) x86_64 GNU/Linux with KDE Plasma 5:142 for Parrot OS.  Thank you.

### Generated Report

Drag your generated report here.
[ckb-next-report-1710126116.gz](https://github.com/ckb-next/ckb-next/files/14553049/ckb-next-report-1710126116.gz)

**Comment by gravityfargo** [comment] 2024-05-01 00:34
Duplicate of #1034

**Closed by gravityfargo** 2024-05-01 00:34 UTC
Labels: new-device
