### ISSUE TITLE
Caps Lock

### ISSUE THREAD

**Issue by tad1073** [ckb-next/ckb-next#442] opened 2019-07-12 09:48 UTC
## General information
There's a lag when enabling and disabling caps lock and the delay is not consistant.
### Source
How and where did you get this program, e.g.:
  * Built manually using quickinstall script.

**Comment by rotarypot** [comment] 2019-07-14 19:52
this might be a duplicate of [issue 303](https://github.com/ckb-next/ckb-next/issues/303)

**Comment by Mario-119** [comment] 2019-07-14 21:00
I have this same issue on my K70 RGB Mk2. It's not just the caps lock, also the num lock and the scroll lock.

**Comment by tatokis** [comment] 2019-08-16 00:43
Duplicate of https://github.com/ckb-next/ckb-next/issues/391

**Closed by tatokis** 2019-08-16 00:43 UTC
Labels: bug
