### ISSUE TITLE
Corsair K100 RGB OPX

### ISSUE THREAD

**Issue by freetz-ng-mod** [ckb-next/ckb-next#726] opened 2021-06-20 06:49 UTC
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/6681846/ckb-next-dev-detect-report.gz)

**Comment by mcrapet** [comment] 2021-06-28 19:29
Duplicate of #651

**Comment by LakesideMiners** [comment] 2021-10-17 15:25
can someone close this? as its a duplicate as said above? @

**Closed** 2021-10-17 15:42 UTC
Labels: new-device
