### ISSUE TITLE
Bug: K70 (old rgb) not detected by software after reboot

### ISSUE THREAD

**Issue by theupriser** [ckb-next/ckb-next#224] opened 2018-08-09 17:25 UTC
With a clean install of OS X 10.13.6 (hackintosh) the keyboard is detected and the keyboard is basically working. When I install CKB-Next the lights go on and the keyboard works like it should. After a reboot or on/off cycle there is no way I'm getting this keyboard working again.
On OS X 10.13.5 literally everything worked with the 0.2.9 version of CKB-Next.

After a reboot I can't login because if the keyboard, there is no input and the caps/numlock lights won't react. So I plug in another keyboard to login and  reinstall the program.. now everything automatically works again.
Everywhere I read that I have to enable the karabiner kext so I put it with KextBeast (from tonymacosx) and let KextBeast do this for me.

Could anyone tell me what I should do?

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2275154/ckb-next-dev-detect-report.gz)

**Comment by tatokis** [comment] 2018-08-09 17:30
Looking at your logs, I don't see any errors, so it's probably not a kext issue. Is this a hackintosh?

When you say the keyboard doesn't work, what do you mean?
Can you control the lights even after you log in with another keyboard?

**Comment by ZirconiumX** [comment] 2018-08-09 17:31
On Thu, 9 Aug 2018, 18:25 Rick Peters, <notifications@github.com> wrote:

> With a clean install of OS X 10.13.6 (hackintosh) the keyboard is detected
> and the keyboard is basically working. When I install CKB-Next the lights
> go on and the keyboard works like it should. After a reboot or on/off cycle
> there is no way I'm getting this keyboard working again.
> On OS X 10.13.5 literally everything worked with the 0.2.9 version of
> CKB-Next.
>

0.2.9 used the userspace Mac backend, which got deprecated precisely
because of the many issues which prove that it does not work.

> After a reboot I can't login because if the keyboard, there is no input
> and the caps/numlock lights won't react. So I plug in another keyboard to
> login and reinstall the program.. now everything automatically works again.
>

You probably have a different kext issue to Karabiner here; this sounds
like a race condition between CKB and the Apple HID driver. But this should
be fixable by a replug.

> Everywhere I read that I have to enable the karabiner kext so I put it
> with KextBeast (from tonymacosx) and let KextBeast do this for me.
>

It's not very difficult to enable manually. We plan to add a popup making
enabling the kext more obvious.

**Comment by theupriser** [comment] 2018-08-09 17:47
> Looking at your logs, I don't see any errors, so it's probably not a kext issue.
When you say the keyboard doesn't work, what do you mean?
Can you control the lights even after you log in with another keyboard?
Can you get it to work by unplugging and replugging it? What if you boot without the keyboard and then plug it in?

Replugging does not work straight after a restart. I just did a sudo kextload org.pqrs..... etc and that also did not work.
the only time I'm getting this to work is after I reinstall de daemon. Maybe by unloading and loading it it's already solved?! 

I think the daemon is not loaded up before the login screen turns up. Is there a way to force loading it when starting Mac?! CKB (gui) is already started and loaded up in the tray after login.

**Comment by tatokis** [comment] 2018-08-09 17:54
If the gui starts without the daemon, it should pop up a window telling you to start the daemon.
Since I have the exact same keyboard, I'll downgrade the firmware and test to see if I can reproduce the issue.

**Comment by theupriser** [comment] 2018-08-09 18:01
Yeah that's what I figured.. i'll try and find out if the daemon is already loaded after a restart in about 10 minutes.. it's loading after the installer for sure.

**Comment by tatokis** [comment] 2018-08-09 19:52
After restarting macOS multiple times, I can't get my K70 to not work.
Which K70 do you have? The original? Rapidfire? (etc)

**Comment by theupriser** [comment] 2018-08-09 21:08
What steps did you take to install and on which version of MacOs are you?
I've downgraded to 10.13.5 in the meantime and it works flawless

**Comment by tatokis** [comment] 2018-08-09 21:14
I'm on 10.12 and I can't really upgrade. I was going to send you a debug build to try and gather more information as to why it happens, but I guess there's no point in that now.

I'm really not sure where to go from here. There is nothing in the logs indicating failure.

**Comment by theupriser** [comment] 2018-08-10 06:58
I'll wait for 10.14 maybe it works there for me..

**Comment by theupriser** [comment] 2018-08-10 07:29
Also the latest version gives me disconnection problems after installing karabiner kext on 10.13.5. should i revert to 0.2.9 again?

**Comment by tatokis** [comment] 2018-08-10 13:34
Can you explain what the "disconnection problems" are?

**Comment by theupriser** [comment] 2018-08-16 15:10
disconection problem has not happened again.. but it still not works after a reboot on 13.6

**Comment by fleischie** [comment] 2018-08-16 21:36
I just tried to replicate the above described behavior to no avail. 😞 

I am using:
- MacBook Pro 13" w/ TouchBar
- macOS 10.13.6
- Corsair K70 RGB (as old as 2016 or so)
- 2.05 firmware on device
- ckb-next 0.3.1-31-g3930617

Multiple attempts to reboot into unusable keyboard did failed. The only thing I noticed, was that when I logged out with ckb-next running my password would be mistyped by default (even with the build-in keyboard on my mac book). A reboot would "fix" this.

**Comment by tatokis** [comment] 2018-08-17 08:40
@theupriser I built the same version @fleischie tested, so give it a shot in case it's something that got fixed without us realising it.
http://ckb-next.info/mac/ckb-next_v0.3.1-31-g3930617_10.11-SDK.dmg

**Comment by theupriser** [comment] 2018-08-17 09:25
I will!

**Comment by theupriser** [comment] 2018-08-17 12:37
So, this works on my MacBook 13.6 (2016). But I noticed it starts the keyboard in bios mode where the download light is flashing (just like it is in bios mode with the switch). That did not happen on my hackintosh. 

I'm looking into trying this on my hackintosh.

**Comment by tatokis** [comment] 2018-08-17 15:00
It automatically switches to BIOS mode on boot for me too. Once the OS boots, it switches back to normal.
I wonder if this is somehow related.

**Comment by theupriser** [comment] 2018-08-17 15:16
yeah but that only happens on my MacBook Pro.. not on my Hackintosh with a normal UEFI!

But now I'm totally confused.. I just updated again to 13.6 on my Hackintosh.. and did not update to the test build linked above.. and you know what?!?! It just works.. don't understand it.. but it just does..

I'll test this out for like a week, maybe 2.. and if it did not crash I will close this issue.. thanks for the help you've given me.

**Comment by theupriser** [comment] 2018-08-20 09:38
Installed FakePCIID to my kexts.. and my problem seems to be solved.. i'll test this further and keep you up to date.

**Comment by theupriser** [comment] 2018-08-21 12:15
It's back again.. now with handoff enabled, i'm not sure what to do anymore.

**Closed** 2018-08-21 12:38 UTC
Labels: device-k70, macOS

**Comment by tatokis** [comment] 2018-08-21 12:39
If it happens again, install this, reboot until the keyboard breaks, hit Generate Report in the GUI and attach it.
http://ckb-next.info/mac/ckb-next_v0.3.1-41-gb25a611_10.11-SDK-handles.dmg

I don't really know either, but this might give more info.
