### ISSUE TITLE
K65 RGB Mini

### ISSUE THREAD

**Issue by solsatra** [ckb-next/ckb-next#987] opened 2023-08-02 12:11 UTC
### What kind of device is it?

Keyboard

### What is the name of the device?

K65 RGB Mini 60% Mechanical keyboard

### Link to Corsair's Product Page

https://www.corsair.com/us/en/p/keyboards/ch-9194014-na/k65-rgb-mini-60-mechanical-gaming-keyboard-cherry-mx-speed-black-ch-9194014-na

### Additional Details

Add any additional details here.

### Generated Report

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/12239868/ckb-next-dev-detect-report.gz)

**Comment by gravityfargo** [comment] 2023-09-12 22:26
Duplicate of #721

**Closed by gravityfargo** 2023-09-12 22:26 UTC
Labels: duplicate, new-device
