### ISSUE TITLE
M65 Pro Back/Forward Binding Bug

### ISSUE THREAD

**Issue by Jass360** [ckb-next/ckb-next#243] opened 2018-08-27 21:07 UTC
Forwards and backwards buttons on the Corsair M65 Pro do not bind properly. Can this be a fixed in a future version?

**Comment by tatokis** [comment] 2018-08-27 21:08
What does "do not bind properly" mean.
Which OS?

**Comment by Jass360** [comment] 2018-08-27 21:10
Sorry - Mac OS High Sierra. Binding as in I select the next and back functions to the forwards and backwards buttons on the side of the mouse. The functions do not seem to be binding, with the standard left click left as default for both buttons.

**Comment by tatokis** [comment] 2018-08-27 21:11
Can you generate a report from the settings tab and attach it?

**Comment by tatokis** [comment] 2018-08-27 21:11
Do keep in mind macOS does not have support for "forwards" and "backwards" by default.

**Comment by Jass360** [comment] 2018-08-27 21:16
[ckb-next-report-1535404389.gz](https://github.com/ckb-next/ckb-next/files/2325649/ckb-next-report-1535404389.gz)

**Comment by Jass360** [comment] 2018-08-27 21:18
So if Mac OS does not have support for these binds, i'm guessing this isn't classed as a bug or anything that could be fixed?

**Comment by Jass360** [comment] 2018-08-27 21:30
Thank you very much for those macros. They do exactly what I wanted the binds to do. From what you're saying, I would say that this is a bug from my set functions not being performed. Thank you for your help - I look forward to future releases!

**Comment by tatokis** [comment] 2018-08-27 21:36
If the macros work when bound to the mouse buttons, then it's not a bug.

Judging by the `They do exactly what I wanted the binds to do.`, it sounds like it does work.
It would've been a bug if pressing the buttons with the macros did absolutely nothing.

Either way, this will be the default behaviour on the next release, so I'm closing this.
If I misunderstood you, then do reply and I will reopen the issue.

**Closed by tatokis** 2018-08-27 21:36 UTC
