### ISSUE TITLE
Corsair K70 CORE RGB

### ISSUE THREAD

**Issue by dacron74** [ckb-next/ckb-next#1053] opened 2024-04-21 08:57 UTC
### What kind of device is it?

Keyboard

### What is the name of the device?

Corsair K70 CORE RGB

### Link to Corsair's Product Page

https://www.corsair.com/de/de/p/keyboards/ch-910981e-de/k70-core-rgb-mechanical-gaming-keyboard-with-palm-rest-black-de-ch-910981e-de#tab-downloads

### Additional Details

Add any additional details here.

### Generated Report

Drag your generated report here.
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/15051231/ckb-next-dev-detect-report.gz)

**Comment by arizonagroovejet** [comment] 2024-04-23 20:58
Here's a report for the same device on Fedora Workstation.
[ckb-next-report-1713905598.gz](https://github.com/ckb-next/ckb-next/files/15082811/ckb-next-report-1713905598.gz)

**Comment by gravityfargo** [comment] 2024-04-30 21:03
Duplicate of #1019

**Closed by gravityfargo** 2024-04-30 21:03 UTC
Labels: new-device, Added to wiki

**Comment by gravityfargo** [comment] 2024-04-30 21:07
Note: This German variant of the K70 CORE RGB shares the same product as the UK variant. This has been annotated in the wiki.
