### ISSUE TITLE
Corsair K70 Core Support

### ISSUE THREAD

**Issue by GerritMo** [ckb-next/ckb-next#1048] opened 2024-03-26 18:23 UTC
### What kind of device is it?

Keyboard

### What is the name of the device?

Corsair K70 Core 

### Link to Corsair's Product Page

https://www.corsair.com/de/de/p/keyboards/ch-910981e-de/k70-core-rgb-mechanical-gaming-keyboard-with-palm-rest-black-de-ch-910981e-de#tab-guides

### Additional Details

Add any additional details here.

### Generated Report

[ckb-next-report-1711477331.gz](https://github.com/ckb-next/ckb-next/files/14763267/ckb-next-report-1711477331.gz)

**Comment by gravityfargo** [comment] 2024-05-01 00:35
Duplicate of #1019

**Closed by gravityfargo** 2024-05-01 00:35 UTC
Labels: new-device
