### ISSUE TITLE
CORSAIR K70 RGB PRO Mechanical Gaming Keyboard

### ISSUE THREAD

**Issue by JPetovello** [ckb-next/ckb-next#998] opened 2023-09-30 14:58 UTC
### What kind of device is it?

Keyboard

### What is the name of the device?

K70 RGB PRO Mechanical Gaming Keyboard

### Link to Corsair's Product Page

https://www.corsair.com/ca/en/p/keyboards/ch-9109410-na/k70-rgb-pro-mechanical-gaming-keyboard-with-pbt-double-shot-pro-keycaps-cherry-mx-red-ch-9109410-na

### Additional Details

Add any additional details here.
idProduct is 0x1bb3
Model is RGP0125

### Generated Report

Drag your generated report here.
[ckb-next-report-1696085587.gz](https://github.com/ckb-next/ckb-next/files/12774959/ckb-next-report-1696085587.gz)

**Comment by gravityfargo** [comment] 2024-04-25 14:43
Duplicate of #865

**Closed by gravityfargo** 2024-04-25 14:43 UTC
Labels: new-device
