### ISSUE TITLE
K95 Platinum light bar not updating properly when switching profiles

### ISSUE THREAD

**Issue by silver246** [ckb-next/ckb-next#718] opened 2021-05-25 17:34 UTC
### Source
* ckb-next 0.4.4 from PPA under Ubuntu 20.04

## What is the program's current behaviour?
At system start or after changing profiles the light bar of the K95 Platinum does not update correctly. 
The lights above the brightness control and volume wheel have wrong colors. 

## What is the expected behaviour of the program?
The light bar gets completely updated when changing profiles.

## Any other notes & comments?
Pressing the brightness button once or changing a color fix the problem. The problem seems only to occur if there is no animation in the profile.

**Comment by Creative-user-name** [comment] 2021-07-14 19:45
Duplicate of #438, so you can close the issue

You might have already done this, but I "solved it" by animation the top bar in the same colour as the static colour. 

And I forgot that that was even a thing after that.

**Closed** 2021-07-14 19:47 UTC
Labels: bug, device-k95-platinum, duplicate
