### ISSUE TITLE
My K70 RGB is not recognized.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ckb-next/ckb-next#928] opened 2023-02-10 22:56 UTC
### Affected Devices

[K70 RGB](http://amazon.co.uk/dp/B09N441FQG?psc=1&ref=ppx_yo2ov_dt_b_product_details)

### Linux Distribution

[`ID="opensuse-tumbleweed"`](cpe:2.3:o:opensuse:tumbleweed:-:*:*:*:*:*:*:*)

### Installation Method

`su -c 'zypper install ckb-next'`

### ckb-next version

[`ckb-next-0.5.0-1.3`](https://download.opensuse.org/repositories/hardware/openSUSE_Tumbleweed/x86_64/ckb-next-0.5.0-34.21.x86_64.rpm)

### What did you expect?

The keyboard should be recognized, per https://github.com/ckb-next/ckb-next/wiki/Supported-Hardware#Keyboards:~:text=K70-,RGB,Supported,-1b13.

### Did you try anything that may have helped?

I reinitialized the relevant computer immediately subsequent to installation.

### Additional Details

I am using [a USB Type-C to Type-C cable](https://www.choetech-europe.com/spd/XCC-1007/Choetech-fast-charging-cable-USB-Type-C-USB-Type-C) rather than the provided USB Type-A to Type-C cable. I haven't verified whether Type-A works, because I am uncertain yet of whether I possess any Type-C to Type-A cables anymore.

![image](https://user-images.githubusercontent.com/42837531/218219176-30197c0c-27ee-46f3-8aaa-264d3e327683.png)

![image](https://user-images.githubusercontent.com/42837531/218219256-276f4752-6566-4d11-a896-d4c907a22b7e.png)

https://github.com/ckb-next/ckb-next/issues/865#issue-1323343226
https://github.com/ckb-next/ckb-next/issues/915#issue-1510413910

### Generated Report

[ckb-next-report-1676069151.gz](https://github.com/ckb-next/ckb-next/files/10711747/ckb-next-report-1676069151.gz)

**Comment by gravityfargo** [comment] 2024-05-01 22:08
Duplicate of #865

**Closed by gravityfargo** 2024-05-01 22:08 UTC
Labels: bug
