### ISSUE TITLE
Support for K95 on Lenovo Legion

### ISSUE THREAD

**Issue by khorser** [ckb-next/ckb-next#375] opened 2019-02-17 09:49 UTC
# New device support request

Hi, Corsair Gaming K95 RGB PLATINUM Keyboard is listed as supported but it seems its laptop version has different vendor and product codes.
Any chance ckb-next can support it?

Attaching ckb-next-dev-detect-report.gz and relevant dmesg extracts

> [    2.621619] usb 1-6: New USB device found, idVendor=048d, idProduct=c935, bcdDevice=13.06
> [    2.621622] usb 1-6: New USB device strings: Mfr=1, Product=2, SerialNumber=0
> [    2.621625] usb 1-6: Product: Corsair Gaming K95 RGB PLATINUM Keyboard
> [    2.621627] usb 1-6: Manufacturer: Corsai
> ...
> [    3.328982] input: Corsai Corsair Gaming K95 RGB PLATINUM Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/0003:048D:C935.0003/input/input19
> [    3.383304] input: Corsai Corsair Gaming K95 RGB PLATINUM Keyboard Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/0003:048D:C935.0003/input/input20
> [    3.383454] input: Corsai Corsair Gaming K95 RGB PLATINUM Keyboard Wireless Radio Control as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/0003:048D:C935.0003/input/input21
> [    3.383598] input: Corsai Corsair Gaming K95 RGB PLATINUM Keyboard System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/0003:048D:C935.0003/input/input22
> [    3.383851] hid-generic 0003:048D:C935.0003: input,hiddev1,hidraw2: USB HID v1.10 Keyboard [Corsai Corsair Gaming K95 RGB PLATINUM Keyboard] on usb-0000:00:14.0-6/input0
> [    3.384905] hid-generic 0003:048D:C935.0004: hiddev2,hidraw3: USB HID v1.10 Device [Corsai Corsair Gaming K95 RGB PLATINUM Keyboard] on usb-0000:00:14.0-6/input1
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2872807/ckb-next-dev-detect-report.gz)

**Comment by tatokis** [comment] 2019-02-17 09:50
Duplicate of https://github.com/ckb-next/ckb-next/issues/330
It is nothing like a K95 Platinum

**Closed by tatokis** 2019-02-17 09:50 UTC
Labels: duplicate
