### ISSUE TITLE
DARK CORE RGB PRO SE - 1b7f

### ISSUE THREAD

**Issue by mandraid** [ckb-next/ckb-next#698] opened 2021-02-07 19:04 UTC
Would it be possible to get this added to the list of supported devices?

**Comment by Ravenslofty** [comment] 2021-02-07 19:22
I think this is a duplicate of #101, unless Corsair have released another Dark Core.

**Comment by mandraid** [comment] 2021-02-07 19:34
I checked here: https://github.com/ckb-next/ckb-next/wiki/Supported-Hardware but did not see it listed.

**Comment by Ravenslofty** [comment] 2021-02-07 19:36
Yes, that's because it's not supported. We have a patch to add support for it, but testers for it have come and gone often enough that it has sat idle for a while now.

**Comment by thoffmeyer0** [comment] 2021-03-03 04:42
I would be interested in giving feedback and such. I run Arch Linux, I also would request support for the k60 keyboard, also willing to test patches.

**Comment by usrtrv** [comment] 2021-03-23 02:28
@Ravenslofty Where's the patch? #101 mentioned the wireless branch but that didn't work for me.

**Comment by Ravenslofty** [comment] 2021-03-23 02:41
The patch *is* the wireless branch. If it doesn't work, we'd appreciate you joining us in IRC so we can get it a step closer to working.

**Comment by medoix** [comment] 2021-05-12 12:23
Happy to help test this out (i have a Dark Core RGB PRO SE) is this the same device being discussed here or an even newer model?
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/6466053/ckb-next-dev-detect-report.gz)

**Closed** 2024-05-01 23:32 UTC
Labels: new-device, Added to wiki, Slipstream Wireless, ✅ wired-support, experimental
