### ISSUE TITLE
Corsair ICUE ls100 not showing up

### ISSUE THREAD

**Issue by i-am-zaidali** [ckb-next/ckb-next#1072] opened 2024-07-06 10:34 UTC
### Describe your situation in detail.

A little background, I live in a 3rd world country where corsair products are extremely expensive,  so i found this dude who made local copies of this controller and it's strips. In windows, the ICUE software properly recognizes it as a "corsair icue ls100" but it doesn't show up in ckb-next even though it is detected in the report

### Generated Report (if applicable)

```
ckb-next-dev-detect - Sat Jul  6 15:08:51 PKT 2024

Kernel: Linux maybe-useful-piece-of-metal 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

OS Version:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

USB Devices:

Bus 003 Device 010: ID 1b1c:0c1e Corsair Smart Lighting Controller
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          239 Miscellaneous Device
  bDeviceSubClass         2 
  bDeviceProtocol         1 Interface Association
  bMaxPacketSize0        64
  idVendor           0x1b1c Corsair
  idProduct          0x0c1e 
  bcdDevice            1.00
  iManufacturer           1 Corsair
  iProduct                2 Smart Lighting Controller
  iSerial                 3 FB66DF55421900F5
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0064
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Association:
      bLength                 8
      bDescriptorType        11
      bFirstInterface         0
      bInterfaceCount         2
      bFunctionClass          2 Communications
      bFunctionSubClass       2 Abstract (modem)
      bFunctionProtocol       0 
      iFunction               0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         2 Communications
      bInterfaceSubClass      2 Abstract (modem)
      bInterfaceProtocol      0 
      iInterface              0 
      CDC Header:
        bcdCDC               1.10
      CDC Call Management:
        bmCapabilities       0x01
          call management
        bDataInterface          1
      CDC ACM:
        bmCapabilities       0x06
          sends break
          line coding and serial state
      CDC Union:
        bMasterInterface        0
        bSlaveInterface         1 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval              64
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass        10 CDC Data
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      28
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)

Dmesg on current boot:
Jul 06 19:57:20.330322 maybe-useful-piece-of-metal kernel: usb 3-1.1.4.3: New USB device found, idVendor=1b1c, idProduct=0c1e, bcdDevice= 1.00
Jul 06 19:57:20.331455 maybe-useful-piece-of-metal kernel: usb 3-1.1.4.3: Manufacturer: Corsair
Jul 06 19:57:20.430320 maybe-useful-piece-of-metal kernel: hid-generic 0003:1B1C:0C1E.0007: hiddev3,hidraw6: USB HID v1.01 Device [Corsair Smart Lighting Controller] on usb-0000:04:00.4-1.1.4.3/input2

Dmesg on last boot:


Daemon on current boot:
Jul 06 15:04:28.936191 maybe-useful-piece-of-metal systemd[1]: Started Corsair Keyboards and Mice Daemon.
Jul 06 15:04:28.938227 maybe-useful-piece-of-metal ckb-next-daemon[9407]: ckb-next-daemon 0.6.0
Jul 06 15:04:28.938708 maybe-useful-piece-of-metal ckb-next-daemon[9407]: [I] Root controller ready at /dev/input/ckb0

Daemon on last boot:
-- No entries --

Dev nodes:
/dev/input/ckb0
/dev/input/ckb0/pid
9407
/dev/input/ckb0/version
0.6.0
/dev/input/ckb0/connected

Kernel command line:
BOOT_IMAGE=/boot/vmlinuz-6.5.0-41-generic root=UUID=36c2c5d4-8ba9-4261-9566-af8f5efaeb02 ro quiet splash vt.handoff=7

GUI ldd:
	linux-vdso.so.1 (0x00007ffc541f9000)
	libdbusmenu-qt5.so.2 => /lib/x86_64-linux-gnu/libdbusmenu-qt5.so.2 (0x00007031da898000)
	libQt5Network.so.5 => /lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007031da44f000)
	libQt5Widgets.so.5 => /lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007031d9c00000)
	libxcb-ewmh.so.2 => /lib/x86_64-linux-gnu/libxcb-ewmh.so.2 (0x00007031da889000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007031da85f000)
	libxcb-screensaver.so.0 => /lib/x86_64-linux-gnu/libxcb-screensaver.so.0 (0x00007031da859000)
	libQt5X11Extras.so.5 => /lib/x86_64-linux-gnu/libQt5X11Extras.so.5 (0x00007031da850000)
	libpulse.so.0 => /lib/x86_64-linux-gnu/libpulse.so.0 (0x00007031da3fa000)
	libquazip5.so.1 => /lib/x86_64-linux-gnu/libquazip5.so.1 (0x00007031da3c4000)
	libQt5DBus.so.5 => /lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007031da330000)
	libQt5Gui.so.5 => /lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007031d9400000)
	libQt5Core.so.5 => /lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007031d8e00000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007031d8a00000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007031d9b19000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007031da310000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007031d8600000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007031da2f4000)
	libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007031d93ac000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007031da846000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007031da83e000)
	libpulsecommon-15.99.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-15.99.so (0x00007031d8d7b000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007031d8d2d000)
	libGL.so.1 => /lib/x86_64-linux-gnu/libGL.so.1 (0x00007031d8ca6000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007031d9ade000)
	libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007031d8931000)
	libmd4c.so.0 => /lib/x86_64-linux-gnu/libmd4c.so.0 (0x00007031da2e2000)
	libdouble-conversion.so.3 => /lib/x86_64-linux-gnu/libdouble-conversion.so.3 (0x00007031da2cd000)
	libicui18n.so.70 => /lib/x86_64-linux-gnu/libicui18n.so.70 (0x00007031d8200000)
	libicuuc.so.70 => /lib/x86_64-linux-gnu/libicuuc.so.70 (0x00007031d8005000)
	libpcre2-16.so.0 => /lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007031d88a7000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007031d8531000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007031d7ecb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007031da8ee000)
	libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007031d7e00000)
	libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007031d937d000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007031da2c3000)
	libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007031d936f000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007031d8c8e000)
	libsndfile.so.1 => /lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007031d7d81000)
	libX11-xcb.so.1 => /lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007031d936a000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007031d7c41000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007031d7b7a000)
	libasyncns.so.0 => /lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007031d9362000)
	libapparmor.so.1 => /lib/x86_64-linux-gnu/libapparmor.so.1 (0x00007031d8c79000)
	libGLdispatch.so.0 => /lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007031d7ac2000)
	libGLX.so.0 => /lib/x86_64-linux-gnu/libGLX.so.0 (0x00007031d8c45000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007031d79fa000)
	libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007031d8880000)
	libicudata.so.70 => /lib/x86_64-linux-gnu/libicudata.so.70 (0x00007031d5c00000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007031d7984000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007031d8c3e000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007031d886c000)
	libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007031d8c2f000)
	libFLAC.so.8 => /lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007031d8830000)
	libvorbis.so.0 => /lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007031d7957000)
	libvorbisenc.so.2 => /lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007031d78ac000)
	libopus.so.0 => /lib/x86_64-linux-gnu/libopus.so.0 (0x00007031d784e000)
	libogg.so.0 => /lib/x86_64-linux-gnu/libogg.so.0 (0x00007031d7843000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007031d5bd5000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007031d7823000)
	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007031d5bca000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007031d5a8c000)
	libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007031d5a7e000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007031d5a58000)
	libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007031d5a35000)

Environment:
QT_ACCESSIBILITY=1
XDG_SESSION_DESKTOP=ubuntu
XDG_SESSION_TYPE=wayland
QT_BEARER_POLL_TIMEOUT=-1
XDG_CURRENT_DESKTOP=ubuntu:GNOME
WAYLAND_DISPLAY=wayland-0
GNOME_SETUP_DISPLAY=:1
DISPLAY=:0
QT_IM_MODULE=ibus
```

**Comment by gravityfargo** [comment] 2024-07-12 23:08
Duplicate of #647

**Closed by gravityfargo** 2024-07-12 23:08 UTC
Labels: question
