### ISSUE TITLE
SCIMITAR PRO RGB mouse is not longer detected as a mouse.

### ISSUE THREAD

**Issue by ecruzreyes** [ckb-next/ckb-next#105] opened 2018-02-22 03:32 UTC
Currently I'm using a K65 RGB RAPIDFIRE keyboard but the mouse is now being listed as a configurable keyboard by CKB, and is working without any light.

I have cloned this repository yesterday and I was able to test and replicate the same issue under Fedora 27 and openSUSE Tumbleweed with same results, both distributions are running Linux 4.15.

[root@yn-zero ckb-next]# cat /dev/input/ckb1/features
corsair k68 rgb pollrate adjrate bind notify fwversion fwupdate hwload
[root@yn-zero ckb-next]# cat /dev/input/ckb2/features
corsair k68 rgb pollrate bind notify fwversion fwupdate hwload

[ckb-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/1746541/ckb-dev-detect-report.gz)
[lsusb_output.txt](https://github.com/ckb-next/ckb-next/files/1746547/lsusb_output.txt)

**Comment by tatokis** [comment] 2018-02-22 08:54
Duplicate of #104

**Closed by tatokis** 2018-02-22 08:54 UTC
Labels: duplicate
