### ISSUE TITLE
Device request for K70 MAX

### ISSUE THREAD

**Issue by XIAIX-code** [ckb-next/ckb-next#1095] opened 2024-09-14 15:38 UTC
### What kind of device is it?

Keyboard

### What is the name of the device?

K70 MAX

### Link to Corsair's Product Page

https://www.corsair.com/us/en/p/keyboards/ch-910961g-na/k70-max-rgb-magnetic-mechanical-gaming-keyboard-adjustable-corsair-mgx-switches-steel-grey-ch-910961g-na

### Additional Details

Add any additional details here.

### Generated Report

Drag your generated report here.
[ckb-next-report-1726328158.gz](https://github.com/user-attachments/files/17002971/ckb-next-report-1726328158.gz)

**Comment by gravityfargo** [comment] 2024-09-19 01:40
Duplicate of #1090

**Closed by gravityfargo** 2024-09-19 01:40 UTC
Labels: new-device
